package com.sun.corba.se.ActivationIDL;


/**
* com/sun/corba/se/ActivationIDL/ServerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../../../src/share/classes/com/sun/corba/se/ActivationIDL/activation.idl
* Tuesday, May 9, 2006 1:28:34 PM PDT
*/

public interface ServerManager extends ServerManagerOperations, com.sun.corba.se.ActivationIDL.Activator, com.sun.corba.se.ActivationIDL.Locator
{
} // interface ServerManager
